spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/cinep_db
    username: cinep_user
    password: cinep_password
  flyway:
    schemas:
      - cinep
server:
  port: 8080
  servlet:
    context-path: /api
logging:
  file:
    path: ./logs
app:
  jwt:
    secret: 3s6v9y$B&E)H@MbQeThWmZq4t7w!z%C*
    durationMin: 60
  api:
      url: "http://www.omdbapi.com/?apikey=99b14a7f&"
      rus-forum: "https://www.forumcinemas.ee/rus/xml/Schedule/?dt="
      eng-forum: "https://www.forumcinemas.ee/eng/xml/Schedule/?dt="
      est-forum: "https://www.forumcinemas.ee/xml/Schedule/?dt="
      rus-apollo: "https://www.apollokino.ee/rus/xml/Schedule/?dt="
      eng-apollo: "https://www.apollokino.ee/eng/xml/Schedule/?dt="
      est-apollo: "https://www.apollokino.ee/xml/Schedule/?dt="
      t1-en: "https://api.cinamonkino.com/xml/Schedule/?id=9989&lang=en-US"
      t1-ru: "https://api.cinamonkino.com/xml/Schedule/?id=9989&lang=ru-RU"
