spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/data/cinepDB
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #dont forget to remove these lines below
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
  servlet:
    context-path: /api
logging:
  file:
    path: ./logs
app:
  jwt:
    secret:
    durationMin: 60
  api:
      url: "http://www.omdbapi.com/?apikey="
      rus-forum: "https://www.forumcinemas.ee/rus/xml/Schedule/?dt="
      eng-forum: "https://www.forumcinemas.ee/eng/xml/Schedule/?dt="
      est-forum: "https://www.forumcinemas.ee/xml/Schedule/?dt="
      rus-apollo: "https://www.apollokino.ee/rus/xml/Schedule/?dt="
      eng-apollo: "https://www.apollokino.ee/eng/xml/Schedule/?dt="
      est-apollo: "https://www.apollokino.ee/xml/Schedule/?dt="
      t1-en: "https://api.cinamonkino.com/xml/Schedule/?id=9989&lang=en-US"
      t1-ru: "https://api.cinamonkino.com/xml/Schedule/?id=9989&lang=ru-RU"