ALTER TABLE USER_BOOKMARKS DROP CONSTRAINT FK_USER_ID;
ALTER TABLE USER_BOOKMARKS DROP CONSTRAINT FK_MOVIE_ID_BOOKMARK;
ALTER TABLE GENRES DROP CONSTRAINT FK_MOVIE_ID;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS USER_BOOKMARKS;
DROP TABLE IF EXISTS MOVIES;
DROP TABLE IF EXISTS GENRES;